
package gui.Admin;

import back.Manage_Products;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bryan V
 */
public class If_ManageProducts extends javax.swing.JFrame {

    //This variable is is for the type of people mange in this interface
    private static TableModel m = new DefaultTableModel();
    private static final String[] columnsNames = {"Id", "Nombre", "Precio c/u" , "Stock"};

    //Update tbl_Cashiers
    private static void updateTable() {
        try {
            
            String[][] data = Manage_Products.getDataProducts("");
            
            m = new DefaultTableModel(data, columnsNames);
            
            tbl_Products.setModel(m);
            
        } catch (SQLException ex) {
            Logger.getLogger(If_ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    //Search a Product through his name
    private static void searchProduct(String nameProduct) {
        
        try {
            
            String[][] data = Manage_Products.getDataProducts(nameProduct);
            m = new DefaultTableModel(data, columnsNames);
            tbl_Products.setModel(m);
            
        } catch (SQLException ex) {
            Logger.getLogger(If_ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * Creates new form If_ManagePeople
     */
    public If_ManageProducts() {
        
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Products = new javax.swing.JTable(){
            //disable edit cells
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }};
            txt_Name = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            btn_NewClient = new javax.swing.JButton();
            btn_EditClient = new javax.swing.JButton();
            btn_Actualizar = new javax.swing.JButton();
            jToolBar1 = new javax.swing.JToolBar();
            menu_Start = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setLocation(new java.awt.Point(0, 0));
            setLocationByPlatform(true);

            btn_Search.setText("Buscar");
            btn_Search.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_SearchActionPerformed(evt);
                }
            });

            tbl_Products.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(tbl_Products);

            txt_Name.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txt_NameActionPerformed(evt);
                }
            });
            txt_Name.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txt_NameKeyReleased(evt);
                }
            });

            jLabel1.setText("Producto:");

            btn_NewClient.setText("Nuevo");
            btn_NewClient.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_NewClientActionPerformed(evt);
                }
            });

            btn_EditClient.setText("Editar");
            btn_EditClient.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_EditClientActionPerformed(evt);
                }
            });

            btn_Actualizar.setText("Actualizar");
            btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_ActualizarActionPerformed(evt);
                }
            });

            jToolBar1.setFloatable(false);
            jToolBar1.setRollover(true);

            menu_Start.setText("Volver");
            menu_Start.setFocusable(false);
            menu_Start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            menu_Start.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            menu_Start.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menu_StartActionPerformed(evt);
                }
            });
            jToolBar1.add(menu_Start);

            jLabel2.setText("lISTA DE PRODUCTOS");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Actualizar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(btn_NewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_EditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Search)
                        .addComponent(btn_NewClient)
                        .addComponent(btn_EditClient)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btn_Actualizar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGap(18, 18, 18))
            );

            layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_EditClient, btn_NewClient, btn_Search, jLabel1, txt_Name});

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        searchProduct(txt_Name.getText().toLowerCase());
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void txt_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NameKeyReleased
        searchProduct(txt_Name.getText().toLowerCase());
    }//GEN-LAST:event_txt_NameKeyReleased

    private void btn_NewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewClientActionPerformed
        
        If_NewProduct men = new If_NewProduct();
        men.PrepareToNewProduct();
        
        men.setVisible(true);
        

    }//GEN-LAST:event_btn_NewClientActionPerformed

    private void btn_EditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditClientActionPerformed
        
        if (tbl_Products.getSelectedRow() != -1) {
            //Send actual select data's person to If_NewPerson
            If_NewProduct men = new If_NewProduct();
            String idProduct = m.getValueAt(tbl_Products.getSelectedRow(), 0).toString(), name = m.getValueAt(tbl_Products.getSelectedRow(), 1).toString();
            String priceU = m.getValueAt(tbl_Products.getSelectedRow(), 2).toString();
            
            men.editProduct(idProduct, name, priceU);
            men.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(rootPane, "Selecione una fila");
        }
        

    }//GEN-LAST:event_btn_EditClientActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        
        updateTable();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void menu_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_StartActionPerformed
        If_Admin men = new If_Admin();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(If_ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(If_ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(If_ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(If_ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new If_ManageProducts().setVisible(true);
                updateTable();
            }
            
        });

        ////////////////////////////////////////MyCode////////////////////////////////////////
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_EditClient;
    private javax.swing.JButton btn_NewClient;
    private javax.swing.JButton btn_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton menu_Start;
    private static javax.swing.JTable tbl_Products;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables
}
