
package gui.Admin;


import back.Manage_People;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bryan Vicente <>
 */
public class If_ManageClients extends javax.swing.JFrame {

    //This variable is is for the type of people mange in this interface
    private static final String typePeople = "Clients";

    private static TableModel m = new DefaultTableModel();
    private static final String[] columnsNames = {"Cedula", "Nombre", "1º Apellido", "2º Apellido", "Dirección", "tlf", "email"};

    private static void updateTable() {
        try {

            String[][] data = Manage_People.getDataPeople("");

            m = new DefaultTableModel(data, columnsNames);

            tbl_Clients.setModel(m);

        } catch (SQLException ex) {
            Logger.getLogger(If_ManageClients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    //Search a client
    private static void searchClients(String cedula) {
        try {
            String[][] data = Manage_People.getDataPeople(cedula);
            m = new DefaultTableModel(data, columnsNames);
            tbl_Clients.setModel(m);
        } catch (SQLException ex) {
            Logger.getLogger(If_ManageClients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //Update tbl_Clients
    /**
     * Creates new form If_ManagePeople
     */
    public If_ManageClients() {

        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Clients = new javax.swing.JTable(){
            //disable edit cells
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        txt_Cedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_NewClient = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_EditClient = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        menu_Start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        btn_Search.setText("Buscar");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        tbl_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Clients);

        txt_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CedulaKeyReleased(evt);
            }
        });

        jLabel1.setText("Cedula:");

        btn_NewClient.setText("Nuevo");
        btn_NewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewClientActionPerformed(evt);
            }
        });

        btn_Delete.setText("Eliminar");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_EditClient.setText("Editar");
        btn_EditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditClientActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        menu_Start.setText("Volver");
        menu_Start.setFocusable(false);
        menu_Start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_Start.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_StartActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_Start);

        jLabel2.setText("lISTA DE CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_NewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_EditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Delete, btn_EditClient, btn_NewClient, btn_Search});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Search)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_NewClient)
                    .addComponent(btn_EditClient)
                    .addComponent(btn_Delete))
                .addGap(18, 18, 18)
                .addComponent(btn_Actualizar)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Actualizar, btn_Delete, btn_EditClient, btn_NewClient, btn_Search, jLabel1, txt_Cedula});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        searchClients(txt_Cedula.getText().trim());
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void txt_CedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CedulaKeyReleased
        searchClients(txt_Cedula.getText().trim());
    }//GEN-LAST:event_txt_CedulaKeyReleased

    private void btn_NewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewClientActionPerformed
        If_NewPerson men = new If_NewPerson();
 
        men.setVisible(true);

    }//GEN-LAST:event_btn_NewClientActionPerformed

    private void btn_EditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditClientActionPerformed

        if (tbl_Clients.getSelectedRow() != -1) {
            If_NewPerson men = new If_NewPerson();
            String cedula = m.getValueAt(tbl_Clients.getSelectedRow(), 0).toString(), name = m.getValueAt(tbl_Clients.getSelectedRow(), 1).toString();
            String surname1 = m.getValueAt(tbl_Clients.getSelectedRow(), 2).toString(), surname2 = m.getValueAt(tbl_Clients.getSelectedRow(), 3).toString();
            String dir = m.getValueAt(tbl_Clients.getSelectedRow(), 4).toString(), tlf = m.getValueAt(tbl_Clients.getSelectedRow(), 5).toString();
            String email = m.getValueAt(tbl_Clients.getSelectedRow(), 6).toString();

         
            men.editPerson(cedula, name, surname1, surname2, dir, tlf, email);

            men.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione una fila");
        }


    }//GEN-LAST:event_btn_EditClientActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        if (tbl_Clients.getSelectedRow() != -1) {
            String cedula = m.getValueAt(tbl_Clients.getSelectedRow(), 0).toString();
            Manage_People.deletePerson(cedula);
            JOptionPane.showMessageDialog(rootPane, "Cliente Eliminado");
            updateTable();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione una fila");
        }
        
        updateTable();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed

        updateTable();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void menu_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_StartActionPerformed
        If_Admin men = new If_Admin();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(If_ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(If_ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(If_ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(If_ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new If_ManageClients().setVisible(true);
                updateTable();
            }

        });

        ////////////////////////////////////////MyCode////////////////////////////////////////
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_EditClient;
    private javax.swing.JButton btn_NewClient;
    private javax.swing.JButton btn_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton menu_Start;
    private static javax.swing.JTable tbl_Clients;
    private javax.swing.JTextField txt_Cedula;
    // End of variables declaration//GEN-END:variables
}
