
package gui.Admin;

import back.Manage_People;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan Vicente
 */
public class If_NewPerson extends javax.swing.JFrame {

    private String cedulaToEdit = "";
    private boolean updatePerson = false;


  

    //set into txt boxs data from selected client 
    public void editPerson(String cedula, String name, String surname1, String surname2, String dir, String tlf, String email) {

        cedulaToEdit = cedula;
        txt_Cedula.setText(cedula);
        txt_Name.setText(name);
        txt_Surname1.setText(surname1);
        txt_Surname2.setText(surname2);
        txt_Dir.setText(dir);
        txt_Email.setText(email);
        txt_Tlf.setText(tlf);

    
        updatePerson = true;

    }

    /**
     * Creates new form If_NewClient
     */
    public If_NewPerson() {

        initComponents();
        lbl_Error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Cedula = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JTextField();
        lbl_Name = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        lbl_Surname1 = new javax.swing.JLabel();
        txt_Surname1 = new javax.swing.JTextField();
        lbl_Dir = new javax.swing.JLabel();
        txt_Dir = new javax.swing.JTextField();
        lbl_Tlf = new javax.swing.JLabel();
        txt_Tlf = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        lbl_Surname2 = new javax.swing.JLabel();
        txt_Surname2 = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_NewPerson = new javax.swing.JButton();
        lbl_Error = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        menu_Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lbl_Cedula.setText("Cedula; ");

        lbl_Name.setText("Nombre:");

        lbl_Surname1.setText("Apelldio 1:");

        lbl_Dir.setText("Dirección:");

        lbl_Tlf.setText("Teléfono:");

        lbl_Email.setText("Email:");

        lbl_Surname2.setText("Apellido 2:");

        btn_Save.setText("Guardar");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_NewPerson.setText("Nuevo");
        btn_NewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewPersonActionPerformed(evt);
            }
        });

        lbl_Error.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Error.setText("Ingrese todos los datos");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        menu_Start.setText("Volver");
        menu_Start.setFocusable(false);
        menu_Start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_Start.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_StartActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_Start);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_NewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Surname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Surname2)
                                    .addComponent(lbl_Cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Surname1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Cedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Tlf)
                            .addComponent(lbl_Dir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Tlf)
                            .addComponent(txt_Email)
                            .addComponent(txt_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Save)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_Cedula, txt_Dir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lbl_Error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cedula)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Dir)
                    .addComponent(txt_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Tlf)
                    .addComponent(txt_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Surname1)
                    .addComponent(txt_Surname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Surname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Surname2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NewPerson)
                    .addComponent(btn_Save))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        String cedula = txt_Cedula.getText();
        //Check if all txt_field are with data
        if (!txt_Cedula.getText().equals("") && !txt_Dir.getText().equals("") && !txt_Email.getText().equals("") && !txt_Name.getText().equals("")
                && !txt_Surname1.getText().equals("") && !txt_Surname2.getText().equals("") && !txt_Tlf.getText().equals("")) {

            if (cedula.length() != 10) {
                JOptionPane.showMessageDialog(rootPane, "La cédula debe tener 10 digitos");
            } else {
                //save data into variables
                String name = txt_Name.getText().trim(), surname1 = txt_Surname1.getText().trim(), surname2 = txt_Surname2.getText().trim();
                String dir = txt_Dir.getText().trim(), tlf = txt_Tlf.getText().trim(), email = txt_Email.getText().trim();
                String turn = "";
           

                //check if the User want to update a Person
                if (updatePerson) {
                    //if the method done incorrectly return a false.
                    if (Manage_People.updatePerson(cedulaToEdit, cedula, name, surname1, surname2, dir, tlf, email, turn)) {
                         JOptionPane.showMessageDialog(rootPane, "Guardado con éxito");
                    }else {
                        
                        lbl_Error.setVisible(true);
                    }

                   
                    this.setVisible(false);
                    
                } else {
                    //Check if the client exist
                    if (!Manage_People.existPerson(cedula)) {
                        
                        if(Manage_People.addNewPerson(cedula, name, surname1, surname2, dir, tlf, email, turn)){
                        JOptionPane.showMessageDialog(rootPane, "Cliente guardado");
                        }else{
                                lbl_Error.setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "El cliente ya existe.");
                    }
                }

                txt_Cedula.setText("");
                txt_Dir.setText("");
                txt_Email.setText("");
                txt_Name.setText("");
                txt_Surname1.setText("");
                txt_Surname2.setText("");
                txt_Tlf.setText("");
                lbl_Error.setVisible(false);
            }
        } else {
            lbl_Error.setVisible(true);
        }


    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_NewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewPersonActionPerformed
        txt_Cedula.setText("");
        txt_Dir.setText("");
        txt_Email.setText("");
        txt_Name.setText("");
        txt_Surname1.setText("");
        txt_Surname2.setText("");
        txt_Tlf.setText("");
    }//GEN-LAST:event_btn_NewPersonActionPerformed

    private void menu_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_StartActionPerformed
      this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_menu_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(If_NewPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(If_NewPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(If_NewPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(If_NewPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new If_NewPerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NewPerson;
    private javax.swing.JButton btn_Save;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_Cedula;
    private javax.swing.JLabel lbl_Dir;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Surname1;
    private javax.swing.JLabel lbl_Surname2;
    private javax.swing.JLabel lbl_Tlf;
    private javax.swing.JButton menu_Start;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Dir;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Surname1;
    private javax.swing.JTextField txt_Surname2;
    private javax.swing.JTextField txt_Tlf;
    // End of variables declaration//GEN-END:variables
}
