package gui.cashier;


import back.Cashier_InvoiceManager;
import back.Manage_People;
import back.Manage_Products;
import gui.Admin.If_NewPerson;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan Vicente <>
 */
public class If_CashierInvoices extends javax.swing.JFrame {

    /**
     * Creates new form If_Cashier
     */

    private static DefaultTableModel modelTable = new DefaultTableModel();
    private static DefaultComboBoxModel modelCBox = new DefaultComboBoxModel();

    public If_CashierInvoices() {
        initComponents();
        newInvoice();

    }

    //search client
    private void searchClient() {
        String cedula = txt_Cedula.getText().toLowerCase();
        //Check if the person exist
        if (cedula.length() == 10 && Manage_People.existPerson(cedula)) {
            try {
                //save data from a person to a String[] and then put into txt boxes
                //Order from data  = cedula, name, surname1, surname2, dir, tlf, email

                String[][] dataPerson = Manage_People.getDataPeople(cedula);
                String name, surname1, surname2, dir, tlf, email;
                name = dataPerson[0][1];
                surname1 = dataPerson[0][2];
                surname2 = dataPerson[0][3];
                dir = dataPerson[0][4];
                tlf = dataPerson[0][5];
                email = dataPerson[0][6];
                txt_Name.setText(name);
                txt_Dir.setText(dir);
                txt_Email.setText(email);
                txt_Surname1.setText(surname1);
                txt_Surname2.setText(surname2);
                txt_Tlf.setText(tlf);

                lbl_ErrorCedula.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(If_CashierInvoices.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (!Manage_People.existPerson(cedula)) {
            If_NewPerson men = new If_NewPerson();
 
            men.setVisible(true);
        }
    }

    private void prepareProductsPanel() {
        try {
            //This funtion prepare the combo box with all products and set the model to product's table added.
            //////////////Prepare combo box//////////////
            String products[][] = back.Manage_Products.getDataProducts("");
            String[] productsToCb = new String[products.length];
            //convert each row and column from products[][] to one row in productsToCb[]

            for (int i = 0; i < productsToCb.length; i++) {
                //format
               // productsToCb[i] = products[i][0] + "|" + products[i][1] + "|" + products[i][2] + "$";
              
                productsToCb[i] = String.format("%-5s | %-40s | %6s", products[i][0], products[i][1] , products[i][2]+"$");
            }
            modelCBox = new DefaultComboBoxModel(productsToCb);
            cb_Products.setModel(modelCBox);

            ////////////// Prepare table  //////////////
            String[] columnNames = {"Id", "Nombre", "P/u", "Cantidad", "Precio Total"};
            modelTable = new DefaultTableModel(columnNames, 0);

            /// add 3 last rows for subtotal , iva and total
            String[] voidLines = {"", "", "", "", ""};
            modelTable.addRow(voidLines);
            modelTable.addRow(voidLines);
            modelTable.addRow(voidLines);

            back.Cashier_InvoiceManager.calculateTotalInTable(modelTable);

            tbl_ProductsAdded.setModel(modelTable);

        } catch (SQLException ex) {
            Logger.getLogger(If_CashierInvoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void eliminateProductFromCbox(String product) {
        modelCBox.removeElement(product);
        cb_Products.setModel(modelCBox);
    }

    //Reset every text and update the Invoice number to make  a new invoice
    private void newInvoice() {
        txt_Cedula.setText("");
        txt_Name.setText("");
        txt_Dir.setText("");
        txt_Email.setText("");
        txt_Surname1.setText("");
        txt_Surname2.setText("");
        txt_Tlf.setText("");
        prepareProductsPanel();
        txt_invoiceVisualization.setText("");
        update_invoiceNumber();
    }

    //update the invoice's number
    private void update_invoiceNumber(){
        int num = Cashier_InvoiceManager.getLastNumInvoice()+1;
        lbl_NInvoice.setText(String.valueOf(num));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_Surname1 = new javax.swing.JTextField();
        txt_Surname2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Dir = new javax.swing.JTextField();
        txt_Tlf = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btn_Edit = new javax.swing.JButton();
        lbl_ErrorCedula = new javax.swing.JLabel();
        PanelProducts = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ProductsAdded = new javax.swing.JTable(){
            //disable edit cells
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        txt_Amount = new javax.swing.JTextField();
        cb_Products = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_AddProduct = new javax.swing.JButton();
        btn_DeleteProduct = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_NInvoice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_MoneyTaken = new javax.swing.JTextField();
        txt_Change = new javax.swing.JTextField();
        lbl_ErrorProducts = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_ErrorProductsStock = new javax.swing.JLabel();
        btn_Calcular = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        PanelInvoiceVision = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_invoiceVisualization = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        menu_Start = new javax.swing.JButton();
        menu_admin = new javax.swing.JButton();
        menu_managePeople = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1415, 785));

        PanelClientData.setBackground(new java.awt.Color(255, 255, 255));
        PanelClientData.setMinimumSize(new java.awt.Dimension(0, 500));

        jLabel1.setText("Cedula:");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 15));

        txt_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CedulaActionPerformed(evt);
            }
        });

        btn_Search.setText("Buscar");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 15));

        jLabel3.setText("Apellido 1:");
        jLabel3.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 15));

        txt_Name.setEditable(false);
        txt_Name.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        txt_Surname1.setEditable(false);
        txt_Surname1.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        txt_Surname2.setEditable(false);
        txt_Surname2.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATOS DEL CLIENTE");

        jLabel9.setText("Apellido 2:");
        jLabel9.setPreferredSize(new java.awt.Dimension(75, 15));

        jLabel10.setText("Dirección:");
        jLabel10.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel10.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel10.setPreferredSize(new java.awt.Dimension(75, 15));

        jLabel12.setText("Teléfono: ");
        jLabel12.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel12.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel12.setPreferredSize(new java.awt.Dimension(75, 15));

        jLabel13.setText("Email:");
        jLabel13.setMaximumSize(new java.awt.Dimension(75, 15));
        jLabel13.setMinimumSize(new java.awt.Dimension(75, 15));
        jLabel13.setPreferredSize(new java.awt.Dimension(75, 15));

        txt_Dir.setEditable(false);
        txt_Dir.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        txt_Tlf.setEditable(false);
        txt_Tlf.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        txt_Email.setEditable(false);
        txt_Email.setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.inactiveForeground"));

        btn_Edit.setText("Editar");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        lbl_ErrorCedula.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ErrorCedula.setText("Ingrese una cedula válida");
        lbl_ErrorCedula.setMaximumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorCedula.setMinimumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorCedula.setPreferredSize(new java.awt.Dimension(75, 15));
        lbl_ErrorCedula.setVisible(false);

        javax.swing.GroupLayout PanelClientDataLayout = new javax.swing.GroupLayout(PanelClientData);
        PanelClientData.setLayout(PanelClientDataLayout);
        PanelClientDataLayout.setHorizontalGroup(
            PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientDataLayout.createSequentialGroup()
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelClientDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClientDataLayout.createSequentialGroup()
                                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ErrorCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelClientDataLayout.createSequentialGroup()
                                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txt_Cedula)
                                    .addComponent(txt_Surname1)
                                    .addComponent(txt_Surname2)
                                    .addComponent(txt_Dir)
                                    .addComponent(txt_Tlf)
                                    .addComponent(txt_Email))
                                .addGap(18, 18, 18)
                                .addComponent(btn_Search)
                                .addGap(40, 40, 40))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(PanelClientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelClientDataLayout.setVerticalGroup(
            PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ErrorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Surname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Surname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(btn_Edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        PanelClientDataLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_Cedula, txt_Dir, txt_Email, txt_Name, txt_Surname1, txt_Surname2, txt_Tlf});

        PanelProducts.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducts.setMinimumSize(new java.awt.Dimension(0, 500));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Productos");

        tbl_ProductsAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ProductsAdded.setShowGrid(false);
        jScrollPane3.setViewportView(tbl_ProductsAdded);

        cb_Products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Cantidad:");

        btn_AddProduct.setText("Añadir");
        btn_AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddProductActionPerformed(evt);
            }
        });

        btn_DeleteProduct.setText("Eliminar Producto");
        btn_DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteProductActionPerformed(evt);
            }
        });

        jButton5.setText("Nueva");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nº  Factura: ");

        lbl_NInvoice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_NInvoice.setText("xxxxxxxxxxxxx");

        jLabel14.setText("Recibido:");

        jLabel15.setText("A devolver:");

        txt_MoneyTaken.setText("0");
        txt_MoneyTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MoneyTakenActionPerformed(evt);
            }
        });
        txt_MoneyTaken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MoneyTakenKeyReleased(evt);
            }
        });

        txt_Change.setEditable(false);
        txt_Change.setText("0");

        lbl_ErrorProducts.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ErrorProducts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ErrorProducts.setText("Ingrese una Cantidad válida");
        lbl_ErrorProducts.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_ErrorProducts.setMaximumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProducts.setMinimumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProducts.setPreferredSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProducts.setVisible(false);

        jLabel16.setText("$");

        jLabel17.setText("$");

        jLabel8.setText("ID - NOMBRE - VALOR");

        lbl_ErrorProductsStock.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ErrorProductsStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ErrorProductsStock.setText("Error: insuficiente stock");
        lbl_ErrorProductsStock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_ErrorProductsStock.setMaximumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProductsStock.setMinimumSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProductsStock.setPreferredSize(new java.awt.Dimension(75, 15));
        lbl_ErrorProductsStock.setVisible(false);

        btn_Calcular.setText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        btn_Save.setText("Guardar");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProductsLayout = new javax.swing.GroupLayout(PanelProducts);
        PanelProducts.setLayout(PanelProductsLayout);
        PanelProductsLayout.setHorizontalGroup(
            PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(2, 2, 2))
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(339, Short.MAX_VALUE))
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_NInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(175, 175, 175))
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProductsLayout.createSequentialGroup()
                                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(39, 39, 39)
                                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MoneyTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(txt_Change))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(PanelProductsLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Calcular))))
                            .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanelProductsLayout.createSequentialGroup()
                                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Amount)
                        .addGap(44, 44, 44)
                        .addComponent(btn_AddProduct)
                        .addContainerGap())
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_DeleteProduct)
                            .addGroup(PanelProductsLayout.createSequentialGroup()
                                .addComponent(lbl_ErrorProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ErrorProductsStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PanelProductsLayout.createSequentialGroup()
                        .addComponent(cb_Products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        PanelProductsLayout.setVerticalGroup(
            PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_NInvoice))
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btn_AddProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ErrorProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ErrorProductsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_DeleteProduct)
                .addGap(18, 18, 18)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_MoneyTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btn_Calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_Change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btn_Save))
                .addContainerGap())
        );

        PanelInvoiceVision.setBackground(new java.awt.Color(255, 255, 255));
        PanelInvoiceVision.setMinimumSize(new java.awt.Dimension(0, 500));

        txt_invoiceVisualization.setEditable(false);
        txt_invoiceVisualization.setColumns(20);
        txt_invoiceVisualization.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_invoiceVisualization.setRows(5);
        jScrollPane1.setViewportView(txt_invoiceVisualization);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Factura");

        javax.swing.GroupLayout PanelInvoiceVisionLayout = new javax.swing.GroupLayout(PanelInvoiceVision);
        PanelInvoiceVision.setLayout(PanelInvoiceVisionLayout);
        PanelInvoiceVisionLayout.setHorizontalGroup(
            PanelInvoiceVisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6)
            .addGroup(PanelInvoiceVisionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelInvoiceVisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(PanelInvoiceVisionLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        PanelInvoiceVisionLayout.setVerticalGroup(
            PanelInvoiceVisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInvoiceVisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        menu_Start.setText("Inicio");
        menu_Start.setFocusable(false);
        menu_Start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_Start.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_StartActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_Start);

        menu_admin.setText("Administración");
        menu_admin.setFocusable(false);
        menu_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_adminActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_admin);

        menu_managePeople.setText("Clientes");
        menu_managePeople.setFocusable(false);
        menu_managePeople.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_managePeople.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_managePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_managePeopleActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_managePeople);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelClientData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(PanelInvoiceVision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelInvoiceVision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelClientData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        searchClient();

    }//GEN-LAST:event_btn_SearchActionPerformed

    private void txt_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CedulaActionPerformed

    private void btn_AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddProductActionPerformed

        try {
            if (!txt_Amount.getText().equals("") && Integer.parseInt(txt_Amount.getText()) > 0) {
                //combine the information from combobox and txt_Amount's data to put into modeltable with Total added
                //get {IdProduct, NameProduct, PriceUnity}

                String[] productData = cb_Products.getSelectedItem().toString().replace("$", "").split("[|]");
                for (int i = 0; i < 3; i++) {
                    productData[i] = productData[i].trim();
                }
                
                int amount = Integer.parseInt(txt_Amount.getText());
                int id = Integer.parseInt(productData[0]);
                //check if there are enought stock
                if (Cashier_InvoiceManager.checkStock(id, amount)) {

                    float total = (float) (Math.round((amount * Float.parseFloat(productData[2])) * 100d) / 100d);
                    String[] productToAdd = {productData[0], productData[1], productData[2], String.valueOf(amount), String.valueOf(total)};
                    int isProductRepeated = -1;

                    //check if there is the same product already in the table and then just add the amount
                    if (modelTable.getRowCount() > 3) {

                        for (int i = 0; i < modelTable.getRowCount() - 3; i++) {

                            int id2 = Integer.parseInt(modelTable.getValueAt(i, 0).toString());
                            if (id == id2) {
                                isProductRepeated = i;
                                break;
                            }
                        }

                    }

                    if (isProductRepeated != -1) {
                        int newAmount = Integer.parseInt(modelTable.getValueAt(isProductRepeated, 3).toString()) + amount;
                        total = (float) (Math.round((newAmount * Float.parseFloat(productData[2])) * 100d) / 100d);
                        modelTable.setValueAt(newAmount, isProductRepeated, 3);
                        modelTable.setValueAt(total, isProductRepeated, 4);

                    } else {

                        //this line is to put the item in the first row and permit the method calculateTotalTable() work correctly
                        String[] voidLines = {"", "", "", "", ""};
                        modelTable.addRow(voidLines);
                        //-4 because must be before that Subtotal row
                        modelTable.setValueAt(productToAdd[0], modelTable.getRowCount() - 4, 0);
                        modelTable.setValueAt(productToAdd[1], modelTable.getRowCount() - 4, 1);
                        modelTable.setValueAt(productToAdd[2], modelTable.getRowCount() - 4, 2);
                        modelTable.setValueAt(productToAdd[3], modelTable.getRowCount() - 4, 3);
                        modelTable.setValueAt(productToAdd[4], modelTable.getRowCount() - 4, 4);

                    }

                    back.Cashier_InvoiceManager.calculateTotalInTable(modelTable);
                    //update the stock
                    int newStock = Manage_Products.getStock(id) - amount;
                    back.Manage_Products.updateStock(id, newStock);

                    tbl_ProductsAdded.setModel(modelTable);
                    txt_Amount.setText("");

                    if (Manage_Products.getStock(id) <= 0) {
                        eliminateProductFromCbox(cb_Products.getSelectedItem().toString());
                    }

                    Cashier_InvoiceManager.printInvoice(txt_invoiceVisualization, modelTable);

                    lbl_ErrorProductsStock.setVisible(false);
                    lbl_ErrorProducts.setVisible(false);
                } else {
                    lbl_ErrorProductsStock.setText("Insuficiente stock:" + Manage_Products.getStock(id) + " restante");
                    lbl_ErrorProductsStock.setVisible(true);
                }

            } else {
                lbl_ErrorProducts.setVisible(true);
            }

        } catch (Exception e) {
            System.out.println(e);

            lbl_ErrorProducts.setVisible(true);
        }
    }//GEN-LAST:event_btn_AddProductActionPerformed

    private void txt_MoneyTakenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MoneyTakenKeyReleased
        //Calculate the money to return
        try {

            String tecla = String.valueOf(evt.getKeyCode());
            // when press intro 
            if (tecla.toLowerCase().equals("10")) {
                float taken = Float.parseFloat(txt_MoneyTaken.getText());
                float total = Float.parseFloat(modelTable.getValueAt(modelTable.getRowCount() - 1, 4).toString());

                Cashier_InvoiceManager.calculateChange(taken, total, txt_Change);

            }
        } catch (NumberFormatException e) {
            txt_Change.setText("ERROR");

        } catch (Exception e) {

        }
    }//GEN-LAST:event_txt_MoneyTakenKeyReleased

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        //Edit client's data
        If_NewPerson men = new If_NewPerson();
        String cedula = txt_Cedula.getText(), name = txt_Name.getText();
        String surname1 = txt_Surname1.getText(), surname2 = txt_Surname2.getText();
        String dir = txt_Dir.getText(), tlf = txt_Tlf.getText();
        String email = txt_Email.getText();

      
        men.editPerson(cedula, name, surname1, surname2, dir, tlf, email);

        men.setVisible(true);
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteProductActionPerformed

        //delete a product from the table and restore the stock
        int nRows = modelTable.getRowCount();
        int rowSelected = tbl_ProductsAdded.getSelectedRow();
        //check if is selected a product
        if (rowSelected <= (nRows - 3)) {
            int id = Integer.parseInt(modelTable.getValueAt(rowSelected, 0).toString());
            int stock = Integer.parseInt(modelTable.getValueAt(rowSelected, 3).toString());

            try {
                //restore the stock
                back.Manage_Products.updateStock(id, Manage_Products.getStock(id) + stock);

                //delete the product from the table and recalculate prices
                modelTable.removeRow(rowSelected);

                Cashier_InvoiceManager.calculateTotalInTable(modelTable);
                tbl_ProductsAdded.setModel(modelTable);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_btn_DeleteProductActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        try {

            // when press intro 
            float taken = Float.parseFloat(txt_MoneyTaken.getText());
            float total = Float.parseFloat(modelTable.getValueAt(modelTable.getRowCount() - 1, 4).toString());

            Cashier_InvoiceManager.calculateChange(taken, total, txt_Change);

        } catch (NumberFormatException e) {
            txt_Change.setText("ERROR");

        }
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void txt_MoneyTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MoneyTakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MoneyTakenActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed

        //save and print the invoice
        if (modelTable.getRowCount() > 3 && txt_Cedula.getText().length() == 10) {
            try {
                Cashier_InvoiceManager.saveInvocie(txt_Cedula.getText(), modelTable);
                newInvoice();
                JOptionPane.showMessageDialog(null, "Guardado exitoso");
                lbl_ErrorCedula.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(If_CashierInvoices.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            lbl_ErrorCedula.setVisible(true);
        }

    }//GEN-LAST:event_btn_SaveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        newInvoice();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void menu_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_StartActionPerformed
        gui.If_Start men = new gui.If_Start();
        men.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_menu_StartActionPerformed

    private void menu_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_adminActionPerformed

        gui.Admin.If_Admin men = new gui.Admin.If_Admin();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_adminActionPerformed

    private void menu_managePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_managePeopleActionPerformed
        gui.Admin.If_ManageClients men = new gui.Admin.If_ManageClients();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_managePeopleActionPerformed
    /*
    ------------
    
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(If_CashierInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(If_CashierInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(If_CashierInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(If_CashierInvoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new If_CashierInvoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelClientData;
    private javax.swing.JPanel PanelInvoiceVision;
    private javax.swing.JPanel PanelProducts;
    private static javax.swing.JButton btn_AddProduct;
    private static javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_DeleteProduct;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Search;
    private javax.swing.JComboBox<String> cb_Products;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_ErrorCedula;
    private javax.swing.JLabel lbl_ErrorProducts;
    private javax.swing.JLabel lbl_ErrorProductsStock;
    private javax.swing.JLabel lbl_NInvoice;
    private javax.swing.JButton menu_Start;
    private javax.swing.JButton menu_admin;
    private javax.swing.JButton menu_managePeople;
    private javax.swing.JTable tbl_ProductsAdded;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Change;
    private javax.swing.JTextField txt_Dir;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MoneyTaken;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Surname1;
    private javax.swing.JTextField txt_Surname2;
    private javax.swing.JTextField txt_Tlf;
    private javax.swing.JTextArea txt_invoiceVisualization;
    // End of variables declaration//GEN-END:variables
}
